# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Twittervision
version:      0.02
version_from: lib/WWW/Twittervision.pm
installdirs:  site
requires:
    JSON:                          2.07
    LWP:                           5.805
    URI:                           1.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
